import keyMirror from 'fbjs/lib/keyMirror';

export default keyMirror({
  READ_TOKEN_SUCCESS: null,
  WRITE_TOKEN_SUCCESS: null,
  REMOVE_TOKEN_SUCCESS: null,

  AUTHENTICATE_USER_DOING: null,
  AUTHENTICATE_USER_SUCCESS: null,
  AUTHENTICATE_USER_FAILURE: null,

  REGISTER_USER_SUCCESS: null,
  REGISTER_USER_FAILURE: null,

  FETCH_BOOK_LIST_DOING: null,
  FETCH_BOOK_LIST_SUCCESS: null,
  FETCH_BOOK_LIST_FAILURE: null,

  FETCH_BOOK_DOING: null,
  FETCH_BOOK_SUCCESS: null,
  FETCH_BOOK_FAILURE: null,

  ADD_COMMENT_SUCCESS: null,
  ADD_COMMENT_FAILURE: null,

  FETCH_USER_BOOKS_DOING: null,
  FETCH_USER_BOOKS_SUCCESS: null,
  FETCH_USER_BOOKS_FAILURE: null,

  FETCH_USER_STARRED_BOOKS_DOING: null,
  FETCH_USER_STARRED_BOOKS_SUCCESS: null,
  FETCH_USER_STARRED_BOOKS_FAILURE: null,

  FETCH_USER_PROFILE_DOING: null,
  FETCH_USER_PROFILE_SUCCESS: null,
  FETCH_USER_PROFILE_FAILURE: null,

  UPDATE_USER_PROFILE_DOING: null,
  UPDATE_USER_PROFILE_SUCCESS: null,
  UPDATE_USER_PROFILE_FAILURE: null,

  STAR_BOOK_DOING: null,
  STAR_BOOK_SUCCESS: null,
  STAR_BOOK_FAILURE: null,

  UNSTAR_BOOK_DOING: null,
  UNSTAR_BOOK_SUCCESS: null,
  UNSTAR_BOOK_FAILURE: null,
});
